### ISSUE TITLE
Angstrom2019 Print 

### ISSUE THREAD

**Issue by il777** [wborgeaud/ctf-writeups#1]
Hello. I am writing in order to clarify one thing about write-up of the task "Print". I wonder how you have found an order of element 'base' in the group of 'palette'. As far as I remember there was not given it in the task.

**Comment by wborgeaud** [comment]
You are right, I wasn't very clear about this. I've updated the writeup with more details. Here is the explanation:
By Lagrange's theorem, we know that the order of `base` is a power of two (since it divides `phi(palette)=2**2047`). By looping over possible orders `2**i, 0<i<2048`, we find that base has order 2045.

**Comment by il777** [comment]
Thank you, now it’s clear for me.
